# Generated by Django 4.2.2 on 2023-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Iot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus_students",
            name="getin",
            field=models.IntegerField(default=1.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_students",
            name="pls",
            field=models.CharField(default=1.3, max_length=100),
            preserve_default=False,
        ),
    ]
