# Generated by Django 4.2.2 on 2023-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Iot", "0002_bus_students_getin_bus_students_pls"),
    ]

    operations = [
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("class_name", models.CharField(max_length=100)),
                ("roll_number", models.IntegerField()),
            ],
        ),
    ]
