# Generated by Django 4.2.2 on 2023-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Iot", "0003_students"),
    ]

    operations = [
        migrations.DeleteModel(
            name="students",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Name",
            new_name="class_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Reg_No",
            new_name="roll_number",
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default=2.4, max_length=100),
            preserve_default=False,
        ),
    ]
