# Generated by Django 4.2.2 on 2023-06-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Iot", "0004_delete_students_rename_name_student_class_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Reg_No", models.IntegerField()),
            ],
        ),
    ]
